# This is an example Mocha config containing every Mocha option plus others
allow-uncaught: false
async-only: false
bail: false
check-leaks: false
color: true
delay: false
diff: true
diagnostics: false
exit: false # could be expressed as "no-exit: true"
extension:
  - js
  - ts
forbid-only: false
forbid-pending: false
full-trace: false
growl: false
inline-diffs: false
# needs to be used with grep or fgrep
# invert: false
recursive: true
reporter: spec
reporter-option:
  - foo=bar
  - baz=quux
require: 'ts-node/register'
retries: 0
slow: 75
sort: false
timeout: 5000 # same as "no-timeout: true" or "timeout: 0"
trace-warnings: true # node flags ok
ui: bdd
v8-stack-trace-limit: 100 # V8 flags are prepended with "v8-"
watch: true
watch-files:
  - 'test/**/*.ts'
  - 'test/**/*.js'
  - 'src/**/*.ts'
  - 'src/**/*.js'
watch-ignore:
  - 'node_modules/'