const GAME_IS_LIVE = 'GAME_IS_LIVE';
const CARD_PLAY = 'CARD_PLAY';
const PLAYER_UPDATE = 'PLAYER_UPDATE';
const MERCHANTRY_UPDATE = 'MERCHANTRY_UPDATE';
const NOTIFICATION = 'NOTIFICATION';
const START_BATTLE = 'START_BATTLE';
const END_BATTLE = 'END_BATTLE';
const TIMER_UPDATE = 'TIMER_UPDATE';

export const messageTypes = [GAME_IS_LIVE, CARD_PLAY, PLAYER_UPDATE, MERCHANTRY_UPDATE, NOTIFICATION, START_BATTLE, END_BATTLE, TIMER_UPDATE].reduce((accum, msg) => {
  accum[msg] = msg;
  return accum;
}, {});
