export enum EVENTBUS_MESSAGE_TYPE {
  STATE_UPDATE = 'UPDATED_STATE',
  PLAYER_UPDATE = 'UPDATE_PLAYER',
  MERCHANTRY_UPDATE = 'MERCHANTRY_UPDATE',
  START_BATTLE = 'START_BATTLE',
  CARD_PLAY = 'CARD_PLAY',
  TIMER_UPDATE = 'TIMER_UPDATE'
}