export enum EVENT_TYPE {
  STATE_UPDATE = 'UPDATED_STATE',
  PLAYER_UPDATE = 'UPDATE_PLAYER',
  MERCHANTRY_UPDATE = 'MERCHANTRY_UPDATE',
  START_BATTLE = 'START_BATTLE',
  CARD_PLAY = 'CARD_PLAY',
  TIMER_UPDATE = 'TIMER_UPDATE'
}

export enum EVENT_SUBTYPE {
  PLAYER_CARD_TO_BOARD = 'PLAYER_CARD_TO_BOARD',
  PLAYER_CARDS_DEALED = 'PLAYER_CARDS_DEALED'
}
